# Generated by Django 5.1.1 on 2024-10-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Date of Birth',
            new_name='date_of_birth',
        ),
    ]
