# Generated by Django 5.1.1 on 2024-10-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_of_birth_profile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile Picture',
            new_name='profile_pic',
        ),
    ]
